steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID', '.']
 
# Step 2: Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID']
 
# Step 3: Create a new Compute Engine Instance Template with the new image
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instance-templates create-with-container todo-app-template-$BUILD_ID \
      --machine-type=e2-micro \
      --tags=todo-app-node \
      --container-image=us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID \
      --boot-disk-size=10GB
 
# Step 4: Apply the new template to the MIG (Zero-Downtime Rolling Update)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'instance-groups'
  - 'managed'
  - 'rolling-action'
  - 'start-update'
  - 'todo-app-mig'
  - '--version=template=todo-app-template-$BUILD_ID'
  - '--zone=us-central1-a'
 
images:
- 'us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID'
 
options:
  logging: CLOUD_LOGGING_ONLY
