steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instance-templates create todo-app-template-$BUILD_ID \
      --machine-type=e2-micro \
      --tags=todo-app-node \
      --image-family=cos-stable \
      --image-project=cos-cloud \
      --boot-disk-size=10GB \
      --metadata=startup-script='#!/bin/bash
      docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
      docker rm -f todo-app || true
      docker run -d -p 8080:8080 --name todo-app us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - instance-groups
  - managed
  - rolling-action
  - replace
  - todo-app-mig
  - "--version=template=todo-app-template-$BUILD_ID"
  - --zone=us-central1-a
  - --max-surge=1
  - --max-unavailable=0

images:
- 'us-central1-docker.pkg.dev/handson-493511/todo-repo/todo-app:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
